# Generated by Django 3.1.5 on 2021-01-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210109_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publication_date',
            new_name='publication_datetime',
        ),
    ]
